server:
  port: 9010
spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ${spring.profiles.active}
    alibaba:
      seata:
        # seata服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
        tx-service-group: my_test_tx_group
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?allowMultiQueries=true
    username: root
    password: 123456
logging:
  level:
    io:
      seata: error